name: QGIS Plugin Tests

on: 
  # [push, pull_request]
  workflow_dispatch: # Включает кнопку ручного запуска в интерфейсе GitHub

jobs:
  test:
    # Запускать job только если текущая ветка — main
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container:
      image: qgis/qgis:release-3_34
      options: --user root

    env:
      # Добавляем пути QGIS и путь к вашей папке ext_libs
      # PYTHONPATH: ${{ github.workspace }}:/usr/share/qgis/python/plugins:/usr/share/qgis/python:${{ github.workspace }}/ext_libs
      # QT_QPA_PLATFORM: offscreen
      # Заменяем ${{ github.workspace }} на родительскую папку, чтобы имя QGIS_VDO стало доступно как модуль
      # PYTHONPATH: /__w/QGIS_VDO:/usr/share/qgis/python/plugins:/usr/share/qgis/python:/__w/QGIS_VDO/QGIS_VDO/ext_libs
      PYTHONPATH: /__w/QGIS_VDO/QGIS_VDO:/usr/share/qgis/python/plugins:/usr/share/qgis/python
      QT_QPA_PLATFORM: offscreen

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Кэширование pip-пакетов внутри Docker-контейнера
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-docker-${{ hashFiles('.github/workflows/test.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-docker-

      # 2. Установка системного виртуального дисплея (если его нет в образе)
      - name: Install system dependencies
        run: |
          apt-get update -qq
          apt-get install -y -qq --no-install-recommends xvfb python3-pip

      # 3. Установка тестового окружения и бинарного bitarray
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest pytest-qgis bitarray

      # 4. Запуск тестов под управлением Xvfb
      - name: Run pytest
        run: |
          xvfb-run -s "+extension GLX -screen 0 1024x768x24" pytest tests/ -v